name: Build and Release

on:
  push:
    branches: [ master, main ]
    tags:
      - 'v*'
  pull_request:
    branches: [ master, main ]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2
      
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v2
      
    - name: Restore NuGet packages
      run: nuget restore ExtractIcon.sln
      
    - name: Build Release
      run: msbuild ExtractIcon.sln /p:Configuration=Release /p:Platform="Any CPU"
      
    - name: Build Debug
      run: msbuild ExtractIcon.sln /p:Configuration=Debug /p:Platform="Any CPU"
      
    - name: Upload Release artifacts
      uses: actions/upload-artifact@v4
      with:
        name: extracticon-release
        path: bin/Release/extracticon.exe
        
    - name: Upload Debug artifacts
      uses: actions/upload-artifact@v4
      with:
        name: extracticon-debug
        path: bin/Debug/extracticon.exe

  release:
    needs: build
    runs-on: windows-latest
    if: startsWith(github.ref, 'refs/tags/v')
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Download artifacts
      uses: actions/download-artifact@v4
      
    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        tag: ${{ github.ref_name }}
        name: ExtractIcon ${{ github.ref_name }}
        body: |
          ExtractIcon ${{ github.ref_name }}
          
          ## What's Changed
          * Check the commit history for changes
          
          ## Installation
          Download `extracticon.exe` from the assets below.
          
          ## Requirements
          - Windows 7 or later
          - .NET Framework 4.8 or later
          - (Optional) ImageMagick for high-quality resizing
          
          ## New Features
          - Debug mode with `-debug` flag for troubleshooting
          - Enhanced icon extraction for Program Files executables
          - Comprehensive diagnostic output
        artifacts: |
          extracticon-release/extracticon.exe
          extracticon-debug/extracticon.exe
        artifactContentType: application/octet-stream
        draft: false
        prerelease: false
        token: ${{ secrets.GITHUB_TOKEN }}