name: Update Latest Release

on:
  push:
    branches: [ master, main ]
    paths:
      - 'src/**'
      - '*.sln'
      - '*.csproj'
      - '.github/workflows/latest-release.yml'

jobs:
  build-and-release:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2
      
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v2
      
    - name: Restore NuGet packages
      run: nuget restore ExtractIcon.sln
      
    - name: Build Release
      run: msbuild ExtractIcon.sln /p:Configuration=Release /p:Platform="Any CPU"
      
    - name: Build Debug
      run: msbuild ExtractIcon.sln /p:Configuration=Debug /p:Platform="Any CPU"
    
    - name: Get commit info
      id: commit
      run: |
        echo "sha_short=$(git rev-parse --short HEAD)" >> $env:GITHUB_OUTPUT
        echo "date=$(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')" >> $env:GITHUB_OUTPUT
        echo "message=$(git log -1 --pretty=%B | Select-Object -First 1)" >> $env:GITHUB_OUTPUT
      
    - name: Delete existing latest release
      uses: dev-drprasad/delete-tag-and-release@v1.0
      with:
        tag_name: latest
        github_token: ${{ secrets.GITHUB_TOKEN }}
        delete_release: true
      continue-on-error: true
      
    - name: Create Latest Release
      uses: ncipollo/release-action@v1
      with:
        tag: latest
        name: Latest Build
        body: |
          ## Latest Build from Master Branch
          
          **Built from commit:** ${{ steps.commit.outputs.sha_short }}
          **Date:** ${{ steps.commit.outputs.date }}
          **Commit message:** ${{ steps.commit.outputs.message }}
          
          This release is automatically updated with every push to the master branch.
          For stable releases, check the [releases page](https://github.com/${{ github.repository }}/releases).
          
          ### Requirements
          - Windows 7 or later
          - .NET Framework 4.6.1 or later
          - (Optional) ImageMagick for high-quality resizing
          
          ### Files
          - `extracticon.exe` - Release build
          - `extracticon-debug.exe` - Debug build with diagnostic output
        artifacts: |
          bin/Release/extracticon.exe
          bin/Debug/extracticon.exe
        artifactContentType: application/octet-stream
        makeLatest: false
        prerelease: true
        allowUpdates: true
        updateOnlyUnreleased: false
        removeArtifacts: true
        replacesArtifacts: true
        token: ${{ secrets.GITHUB_TOKEN }}